title: "The Escape Archive"
description: "Reviewing the best and darkest escape rooms."
# Ersetze das hier mit DEINER echten GitHub-Adresse
url: "https://nairolf22.github.io"
# Das hier muss leer bleiben (nur Anf√ºhrungszeichen)
baseurl: ""
permalink: /reviews/:title/

# Aktiviert Markdown
markdown: kramdown
theme: null

collections:
  reviews:
    output: true
