url: "https://www.escapearchive.de"
baseurl: ""
title: "The Escape Archive"
description: "Reviewing the best and darkest escape rooms."
permalink: /reviews/:title/

# Aktiviert Markdown
markdown: kramdown
theme: null

collections:
  reviews:
    output: true
